FPS = 60

WIDTH = 420
HEIGHT = 400

MAX_MESSAGES = 50

CHAT_SPEED = 0.6
FADE_SPEED = 0.02

MESSAGE_MAX_WIDTH = 350
USERNAME_MAX_WIDTH = 320

TTS_ENABLED = False
TTS_MIN_LENGTH = 3
TTS_READ_MAIN_ONLY = True
TTS_READ_USER_NAME = True
TTS_MAX_LENGTH = 0
TTS_READ_MIDDLE_NAME = "說"
TTS_INTERRUPT_CURRENT = True
TTS_MAX_QUEUE_SIZE = 0
TTS_QUEUE_OVERFLOW_ACTION = 0
TTS_LANGUAGE = "zh-TW"
TTS_VOICE_IDENTIFIER = ""
TTS_RATE = 0.0
TTS_PITCH = 0.0
TTS_VOLUME = 0.0